name: topefind

channels:
  - conda-forge
  - bioconda
  - sdvillal

dependencies:
  # General
  - python>=3.10
  - backports
  - requests
  - tqdm
  - pip

  # Development
  - pytest
  - pytest-cov
  - ruff

  # Machine Learning
  - transformers<=4.31.0
  - sentencepiece
  - protobuf
  - scikit-learn
  - pytorch
  - numpy
  - scipy
  - einops

  # Data Related
  - polars<=0.16.10
  - pandas

  # Bioinformatics
  - biotite
  # Do not update this until this ANARCI bug is fixed:
  # https://github.com/oxpig/ANARCI/issues/17
  - anarci==2020.04.23

  # Visualizations
  - tabulate
  - matplotlib
  - seaborn
  - plotly
  - python-kaleido
  - panel<=0.14.4

  - pip:
      - "-e ."